#### 백준#2588
(세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.<br>
![Alt text](image.png)<br>
(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.

In [2]:
m, n = map(int, input().split())

print(f'3: {m * ((n // 1) % 10)}')      # (n // 10 ** 0) % 10
print(f'4: {m * ((n // 10) % 10)}')     # (n // 10 ** 1) % 10
print(f'5: {m * ((n // 100) % 10)}')    # (n // 10 ** 2) % 10
print(f'6: {m * n}')

3: 2360
4: 3776
5: 1416
6: 181720


#### 백준#25304
준원이는 저번 주에 살면서 처음으로 코스트코를 가 봤다. 정말 멋졌다. 그런데, 몇 개 담지도 않았는데 수상하게 높은 금액이 나오는 것이다! 준원이는 영수증을 보면서 정확하게 계산된 것이 맞는지 확인해보려 한다.

영수증에 적힌,

- 구매한 각 물건의 가격과 개수
- 구매한 물건들의 총 금액

을 보고, 구매한 물건의 가격과 개수로 계산한 총 금액이 영수증에 적힌 총 금액과 일치하는지 검사해보자.

In [3]:
X = int(input())    # 260000
N = int(input())    # 4
receipt = []
for i in range(N):
    a, b = map(int, input().split())
    receipt.append((a, b))

In [4]:
receipt

[(20000, 5), (30000, 2), (10000, 6), (5000, 8)]

In [5]:
costco_sum = 0
for a, b in receipt:
    costco_sum += a * b
print(costco_sum)

260000


#### 백준#2562
9개의 서로 다른 자연수가 주어질 때, 이들 중 최댓값을 찾고 그 최댓값이 몇 번째 수인지를 구하는 프로그램을 작성하시오.

예를 들어, 서로 다른 9개의 자연수

3, 29, 38, 12, 57, 74, 40, 85, 61

이 주어지면, 이들 중 최댓값은 85이고, 이 값은 8번째 수이다.

In [6]:
c = [3, 29, 38, 12, 57, 74, 40, 85, 61]
cmax, cindex = -1, -1
for index, element in enumerate(c):
    if cmax < element:
        cmax = element
        cindex = index
print(f'index={cindex}, {cindex+1}번째 값, {cmax}')

index=7, 8번째 값, 85


#### 백준#2675
문자열 S를 입력받은 후에, 각 문자를 R번 반복해 새 문자열 P를 만든 후 출력하는 프로그램을 작성하시오. 

즉, 첫 번째 문자를 R번 반복하고, 두 번째 문자를 R번 반복하는 식으로 P를 만들면 된다. S에는 QR Code "alphanumeric" 문자만 들어있다.

첫째 줄에 테스트 케이스의 개수 T(1 ≤ T ≤ 1,000)가 주어진다.<br>
각 테스트 케이스는 반복 횟수 R(1 ≤ R ≤ 8), 문자열 S가 공백으로 구분되어 주어진다. S의 길이는 적어도 1이며, 20글자를 넘지 않는다. 

In [7]:
T = int(input())
test_case = []
for _ in range(T):
    cmd = input().split()
    test_case.append(cmd)
print(test_case)

[['3', 'ABC'], ['5', '/HTP']]


In [9]:
for R, S in test_case:
    result = ''
    r = int(R)
    for s in S:
        result += s * r 
    print(result)

AAABBBCCC
/////HHHHHTTTTTPPPPP


#### 백준#10809
알파벳 소문자로만 이루어진 단어 S가 주어진다. 각각의 알파벳에 대해서, 단어에 포함되어 있는 경우에는 처음 등장하는 위치를, 포함되어 있지 않은 경우에는 -1을 출력하는 프로그램을 작성하시오.

In [2]:
chr(ord('a') + 1)

'b'

In [10]:
char_dict = {}
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = -1
print(char_dict)

{'a': -1, 'b': -1, 'c': -1, 'd': -1, 'e': -1, 'f': -1, 'g': -1, 'h': -1, 'i': -1, 'j': -1, 'k': -1, 'l': -1, 'm': -1, 'n': -1, 'o': -1, 'p': -1, 'q': -1, 'r': -1, 's': -1, 't': -1, 'u': -1, 'v': -1, 'w': -1, 'x': -1, 'y': -1, 'z': -1}


In [11]:
word = 'baekjoon'
for i in range(26):
    c = chr(ord('a') + i)
    print(word.find(c), end=' ')

1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [12]:
char_dict = {}
word = 'a quick brown fox'
for i in range(26):
    c = chr(ord('a') + i)
    char_dict[c] = word.find(c)     # find()는 찾는 문자열이 없으면 -1을 리턴함
print(char_dict)

{'a': 0, 'b': 8, 'c': 5, 'd': -1, 'e': -1, 'f': 14, 'g': -1, 'h': -1, 'i': 4, 'j': -1, 'k': 6, 'l': -1, 'm': -1, 'n': 12, 'o': 10, 'p': -1, 'q': 2, 'r': 9, 's': -1, 't': -1, 'u': 3, 'v': -1, 'w': 11, 'x': 16, 'y': -1, 'z': -1}


#### 백준#2908
상근이의 동생 상수는 수학을 정말 못한다. 상수는 숫자를 읽는데 문제가 있다. 이렇게 수학을 못하는 상수를 위해서 상근이는 수의 크기를 비교하는 문제를 내주었다. 상근이는 세 자리 수 두 개를 칠판에 써주었다. 그 다음에 크기가 큰 수를 말해보라고 했다.

상수는 수를 다른 사람과 다르게 거꾸로 읽는다. 예를 들어, 734와 893을 칠판에 적었다면, 상수는 이 수를 437과 398로 읽는다. 따라서, 상수는 두 수중 큰 수인 437을 큰 수라고 말할 것이다.

두 수가 주어졌을 때, 상수의 대답을 출력하는 프로그램을 작성하시오.

첫째 줄에 상근이가 칠판에 적은 두 수 A와 B가 주어진다. 두 수는 같지 않은 세 자리 수이며, 0이 포함되어 있지 않다.

In [13]:
for i in range(3):
    m, n = input().split()
    m_, n_ = int(m[::-1]), int(n[::-1])
    max_val = m_ if m_ >= n_ else n_
    print(f'{m}, {n}: {max_val}')

734, 893: 437
221, 231: 132
839, 237: 938


#### 백준#3003
동혁이는 오래된 창고를 뒤지다가 낡은 체스판과 피스를 발견했다.

체스판의 먼지를 털어내고 걸레로 닦으니 그럭저럭 쓸만한 체스판이 되었다. 하지만, 검정색 피스는 모두 있었으나, 흰색 피스는 개수가 올바르지 않았다.

체스는 총 16개의 피스를 사용하며, 킹 1개, 퀸 1개, 룩 2개, 비숍 2개, 나이트 2개, 폰 8개로 구성되어 있다.

동혁이가 발견한 흰색 피스의 개수가 주어졌을 때, 몇 개를 더하거나 빼야 올바른 세트가 되는지 구하는 프로그램을 작성하시오.

In [15]:
# king, queen, rook, bishop, knight, pawn
chess_pieces = [1, 1, 2, 2, 2, 8]
pieces = list(map(int, input().split()))
for i in range(len(chess_pieces)):
    print(chess_pieces[i] - pieces[i], end=' ')

1 0 0 0 0 1 

#### 백준#2444
다음은 입력값이 5인 경우의 예이다. 예제를 보고 규칙을 유추한 뒤에 별을 찍어 보세요.
<pre>
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
</pre>

In [18]:
N = 5
for i in range(N):
    line = ' ' * (N - i - 1) + '*' * (2 * i + 1)
    print(line)
for i in range(1, N):
    line = ' ' * i + '*' * (2 * (N - i) - 1)
    print(line)

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


#### 백준#1157
알파벳 대소문자로 된 단어가 주어지면, 이 단어에서 가장 많이 사용된 알파벳이 무엇인지 알아내는 프로그램을 작성하시오. 단, 대문자와 소문자를 구분하지 않는다.

In [19]:
alpha_dict = {}
string = 'A quick brown fox jumps over the lazy dog'
for i in range(26):
    c = chr(ord('a') + i)
    alpha_dict[c] = string.lower().count(c)
print(alpha_dict)

{'a': 2, 'b': 1, 'c': 1, 'd': 1, 'e': 2, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 1, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


In [20]:
alpha_items = list(alpha_dict.items())
alpha_items.sort(key=lambda x: x[1], reverse=True)
alpha_items[:5]

[('o', 4), ('a', 2), ('e', 2), ('r', 2), ('u', 2)]

#### 백준#2738
N*M크기의 두 행렬 A와 B가 주어졌을 때, 두 행렬을 더하는 프로그램을 작성하시오.

첫째 줄에 행렬의 크기 N 과 M이 주어진다. 둘째 줄부터 N개의 줄에 행렬 A의 원소 M개가 차례대로 주어진다. 이어서 N개의 줄에 행렬 B의 원소 M개가 차례대로 주어진다. N과 M은 100보다 작거나 같고, 행렬의 원소는 절댓값이 100보다 작거나 같은 정수이다.

In [21]:
A = [[1, 1, 1], [2, 2, 2], [0, 1, 0]]
B = [[3, 3, 3], [4, 4, 4], [5, 5, 100]]
C = []
for i in range(len(A)):
    temp = []
    for k in range(len(A[i])):
        temp.append(A[i][k] + B[i][k])
    C.append(temp)

for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


In [22]:
C = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A)):
    for k in range(len(A[i])):
        C[i][k] = A[i][k] + B[i][k]

for i in range(len(C)):
    for k in range(len(C[i])):
        print(C[i][k], end=' ')
    print()

4 4 4 
6 6 6 
5 6 100 


- Numpy를 사용해야 하는 이유

In [23]:
import numpy as np
A = np.array([[1, 1, 1], [2, 2, 2], [0, 1, 0]])
print(A)

[[1 1 1]
 [2 2 2]
 [0 1 0]]


In [24]:
B = np.array([[3, 3, 3], [4, 4, 4], [5, 5, 100]])
print(B)

[[  3   3   3]
 [  4   4   4]
 [  5   5 100]]


In [25]:
# 벡터화 연산
C = A + B
print(C)

[[  4   4   4]
 [  6   6   6]
 [  5   6 100]]
